encoding:       'utf-8'
markdown:       kramdown
highlighter:    pygments
title:          ACM HONORED CLASS
baseurl:        ""
url:            ""
permalink:      /:categories/:title.html
gems: [jekyll-paginate]

footer:
      
copyright:
    - Design by ACM HONORED CLASS
    - "&copy; Copyright 2016, ACM HONORED CLASS. All Rights Reserved."
      
css:
    - /lib/style.css
    - /lib/syntax.css
    - /lib/buttons.css
    
