encoding:       'utf-8'
markdown:       kramdown
highlighter:    pygments
title:          Sidi Lu
baseurl:        ""
url:            ""
permalink:      /:categories/:title.html
gems: [jekyll-paginate]

footer:
      
copyright:
    - Redesign by Sidi Lu
    - "&copy; Copyright 2018, ACM HONORED CLASS. All Rights Reserved."
      
css:
    - /lib/style.css
    - /lib/syntax.css
    - /lib/buttons.css
    
